# Detect which parts of the TREXIO API the TREXIO in use provides.
#
# Older TREXIO releases lack some fields, e.g. the dipole integrals. Each
# function trexio-validate uses is looked up in trexio.h; the required ones must
# be there, and each optional one gets a TV_HAVE_<function> macro in
# trexio_validate_features.h, which gates the code reading it. Only the header
# is needed, so this also works when TREXIO is built as part of this project.
#
# Inputs: TREXIO_VALIDATE_TREXIO_PROVIDER and the variables of
# TrexioValidateDependencies.cmake. Output: the directory
# TREXIO_VALIDATE_FEATURES_DIR containing trexio_validate_features.h.

include(CheckSymbolExists)

# Include directories that contain trexio.h.
if(TREXIO_VALIDATE_TREXIO_PROVIDER STREQUAL "config")
  get_target_property(_tv_inc trexio::trexio INTERFACE_INCLUDE_DIRECTORIES)
elseif(TREXIO_VALIDATE_TREXIO_PROVIDER STREQUAL "pkgconfig")
  set(_tv_inc ${TREXIO_PC_INCLUDE_DIRS})
elseif(TREXIO_VALIDATE_TREXIO_PROVIDER STREQUAL "path")
  set(_tv_inc "${TREXIO_INCLUDE_DIR}")
else()
  set(_tv_inc "${trexio_SOURCE_DIR}/include")
endif()
if(NOT _tv_inc)
  set(_tv_inc "")
endif()

# Forget earlier results when the header changes, e.g. after switching TREXIO.
find_file(_tv_header trexio.h HINTS ${_tv_inc} NO_CACHE)
if(NOT _tv_header)
  message(FATAL_ERROR "trexio.h not found (searched ${_tv_inc} and the default paths)")
endif()
file(SHA256 "${_tv_header}" _tv_hash)
if(NOT _tv_hash STREQUAL TREXIO_VALIDATE_FEATURES_HASH)
  get_cmake_property(_tv_cached CACHE_VARIABLES)
  foreach(_v IN LISTS _tv_cached)
    if(_v MATCHES "^TV_HAVE_")
      unset(${_v} CACHE)
    endif()
  endforeach()
  set(TREXIO_VALIDATE_FEATURES_HASH "${_tv_hash}" CACHE INTERNAL "")
endif()

# Declarations only: compile, do not link.
set(CMAKE_REQUIRED_INCLUDES ${_tv_inc})
set(CMAKE_REQUIRED_QUIET ON)
set(_tv_saved_target_type "${CMAKE_TRY_COMPILE_TARGET_TYPE}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# ------------------------------------------------------------ required

set(_tv_required trexio_open trexio_close trexio_string_of_error)
foreach(_f
    nucleus_num nucleus_charge nucleus_coord nucleus_repulsion
    electron_up_num electron_dn_num
    basis_type basis_prim_num basis_shell_num basis_nucleus_index basis_shell_ang_mom
    basis_shell_factor basis_shell_index basis_exponent basis_coefficient basis_prim_factor
    ao_cartesian ao_num ao_shell ao_normalization
    mo_num mo_coefficient mo_occupation
    ao_1e_int_overlap ao_1e_int_kinetic ao_1e_int_potential_n_e ao_1e_int_core_hamiltonian
    mo_1e_int_overlap mo_1e_int_kinetic mo_1e_int_potential_n_e mo_1e_int_core_hamiltonian
    ao_2e_int_eri ao_2e_int_eri_size mo_2e_int_eri mo_2e_int_eri_size)
  list(APPEND _tv_required trexio_read_${_f})
endforeach()

# One compilation for all of them; only if it fails are they looked up one
# by one, to name what is missing.
set(_tv_src "#include <trexio.h>\nint main(void) {\n  void* p[] = {\n")
foreach(_f IN LISTS _tv_required)
  string(APPEND _tv_src "    (void*) &${_f},\n")
endforeach()
string(APPEND _tv_src "  };\n  return p[0] == 0;\n}\n")
include(CheckCSourceCompiles)
check_c_source_compiles("${_tv_src}" TV_HAVE_REQUIRED_TREXIO_API)
if(NOT TV_HAVE_REQUIRED_TREXIO_API)
  set(_tv_missing)
  foreach(_f IN LISTS _tv_required)
    check_symbol_exists(${_f} trexio.h TV_HAVE_${_f})
    if(NOT TV_HAVE_${_f})
      list(APPEND _tv_missing ${_f})
    endif()
  endforeach()
  list(JOIN _tv_missing ", " _tv_missing)
  message(FATAL_ERROR
    "The TREXIO in ${_tv_header} lacks functions trexio-validate needs: "
    "${_tv_missing}. TREXIO 2.1 or later is required.")
endif()

# ------------------------------------------------------------ optional

set(_tv_optional
  TREXIO_AUTO
  trexio_has_pbc_periodic
  trexio_read_electron_num
  trexio_read_basis_r_power
  trexio_has_basis_exponent_im
  trexio_has_basis_coefficient_im
  trexio_has_basis_oscillation_arg
  trexio_has_ecp
  trexio_has_ecp_num
  trexio_read_mo_coefficient_im
  trexio_read_mo_spin
  trexio_read_mo_k_point
  trexio_read_ao_1e_int_dipole_x
  trexio_read_ao_1e_int_dipole_y
  trexio_read_ao_1e_int_dipole_z
  trexio_read_mo_1e_int_dipole_x
  trexio_read_mo_1e_int_dipole_y
  trexio_read_mo_1e_int_dipole_z)

set(_tv_header_text "/* Generated by CMake: the optional TREXIO functions available. */\n")
set(_tv_absent)
foreach(_f IN LISTS _tv_optional)
  check_symbol_exists(${_f} trexio.h TV_HAVE_${_f})
  if(TV_HAVE_${_f})
    string(APPEND _tv_header_text "#define TV_HAVE_${_f} 1\n")
  else()
    string(APPEND _tv_header_text "#define TV_HAVE_${_f} 0\n")
    list(APPEND _tv_absent ${_f})
  endif()
endforeach()
if(_tv_absent)
  list(JOIN _tv_absent ", " _tv_absent_text)
  message(STATUS "TREXIO lacks the optional ${_tv_absent_text}")
endif()

set(TREXIO_VALIDATE_FEATURES_DIR "${PROJECT_BINARY_DIR}/generated")
file(CONFIGURE OUTPUT "${TREXIO_VALIDATE_FEATURES_DIR}/trexio_validate_features.h"
  CONTENT "${_tv_header_text}" @ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE "${_tv_saved_target_type}")
unset(CMAKE_REQUIRED_INCLUDES)
unset(CMAKE_REQUIRED_QUIET)
